### ISSUE TITLE
sync fails?

### ISSUE THREAD

**Issue by jjkoehorst** [cyverse/gocommands#31]
I am working on a data cluster and I want to sync some data to iRODS, gocmd works great when using put but when using sync I get the following 

```
[koehorst@int4 ~]$ ./gocmd sync --progress /gpfs/work2/0/gs/raw_data/mindset/16s/ i:/unlock/home/a_folder/data/
bundle 0 - Cleaning & making dirs        ... done! [50 in 170ms]
bundle 1 - Cleaning & making dirs        ... done! [50 in 120ms]
bundle 0 - Bundling                      ... done! [102.48M in 920ms]
bundle 2 - Cleaning & making dirs        ... done! [50 in 140ms]
bundle 1 - Bundling                      ...  0.0% [..................] [0 in 600ms]
bundle 0 - Uploading                     ...  0.0% [..................] [0B in 300ms]
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 237 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc000490150}, {0xc000422020, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc00044d918?, 0xc0004a8830?}, {0xc000422020, 0x8, 0x8}, {0xc005a80000, 0x2800000, 0x2800000}, {0xc02b280000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc000422020, 0x8, 0x8}, {0xc005a80000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc0001fe000, {0xc000422020, 0x8, 0x8}, {0xc005a80000, 0x2800000, 0x2800000}, {0xc02b280000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc00044df70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0xc0004a9140?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 233 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc000910030}, {0xc0003aa010, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc00035f918?, 0xc0001e0070?}, {0xc0003aa010, 0x8, 0x8}, {0xc000a80000, 0x2800000, 0x2800000}, {0xc05fa80000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc0003aa010, 0x8, 0x8}, {0xc000a80000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc000424100, {0xc0003aa010, 0x8, 0x8}, {0xc000a80000, 0x2800000, 0x2800000}, {0xc05fa80000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc00035ff70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0x1?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 229 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc000a02030}, {0xc00084a000, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc00044f918?, 0xc000736010?}, {0xc00084a000, 0x8, 0x8}, {0xc003280000, 0x2800000, 0x2800000}, {0xc05aa80000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc00084a000, 0x8, 0x8}, {0xc003280000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc0001fe100, {0xc00084a000, 0x8, 0x8}, {0xc003280000, 0x2800000, 0x2800000}, {0xc05aa80000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc00044ff70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0x0?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 239 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc000832060}, {0xc00072c000, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc000769918?, 0xc0003aa030?}, {0xc00072c000, 0x8, 0x8}, {0xc017280000, 0x2800000, 0x2800000}, {0xc064a80000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc00072c000, 0x8, 0x8}, {0xc017280000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc000594080, {0xc00072c000, 0x8, 0x8}, {0xc017280000, 0x2800000, 0x2800000}, {0xc064a80000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc000769f70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0xc00031afa0?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 228 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc000990090}, {0xc00002a0b0, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc000571918?, 0xc0002e60b0?}, {0xc00002a0b0, 0x8, 0x8}, {0xc008280000, 0x2800000, 0x2800000}, {0xc021280000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc00002a0b0, 0x8, 0x8}, {0xc008280000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc0001fe180, {0xc00002a0b0, 0x8, 0x8}, {0xc008280000, 0x2800000, 0x2800000}, {0xc021280000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc000571f70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0x1?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 64 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc000994210}, {0xc0008fbef0, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc000767918?, 0xc000422040?}, {0xc0008fbef0, 0x8, 0x8}, {0xc00fa80000, 0x2800000, 0x2800000}, {0xc055a80000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc0008fbef0, 0x8, 0x8}, {0xc00fa80000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc000158400, {0xc0008fbef0, 0x8, 0x8}, {0xc00fa80000, 0x2800000, 0x2800000}, {0xc055a80000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc000767f70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0x0?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 236 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc0002e5cb0}, {0xc0004a8040, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc000565918?, 0xc000870010?}, {0xc0004a8040, 0x8, 0x8}, {0xc014a80000, 0x2800000, 0x2800000}, {0xc050a80000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc0004a8040, 0x8, 0x8}, {0xc014a80000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc000764000, {0xc0004a8040, 0x8, 0x8}, {0xc014a80000, 0x2800000, 0x2800000}, {0xc050a80000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc000565f70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0xc0004a9120?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 235 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc000580090}, {0xc000870168, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc00034d918?, 0xc00002a0c0?}, {0xc000870168, 0x8, 0x8}, {0xc012280000, 0x2800000, 0x2800000}, {0xc03ca80000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc000870168, 0x8, 0x8}, {0xc012280000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc000424000, {0xc000870168, 0x8, 0x8}, {0xc012280000, 0x2800000, 0x2800000}, {0xc03ca80000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc00034df70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0x0?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 234 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc0009ce060}, {0xc000870160, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc000569918?, 0xc00072c020?}, {0xc000870160, 0x8, 0x8}, {0xc01c280000, 0x2800000, 0x2800000}, {0xc04ba80000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc000870160, 0x8, 0x8}, {0xc01c280000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc000420000, {0xc000870160, 0x8, 0x8}, {0xc01c280000, 0x2800000, 0x2800000}, {0xc04ba80000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc000569f70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0x0?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 238 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc000396060}, {0xc000870148, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc0004e9918?, 0xc00062c030?}, {0xc000870148, 0x8, 0x8}, {0xc00aa80000, 0x2800000, 0x2800000}, {0xc030280000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc000870148, 0x8, 0x8}, {0xc00aa80000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc0003b0000, {0xc000870148, 0x8, 0x8}, {0xc00aa80000, 0x2800000, 0x2800000}, {0xc030280000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc0004e9f70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0xc0003167a0?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 231 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc0003bc030}, {0xc000422010, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc000351918?, 0xc0006c6010?}, {0xc000422010, 0x8, 0x8}, {0xc01ea80000, 0x2800000, 0x2800000}, {0xc044280000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc000422010, 0x8, 0x8}, {0xc01ea80000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc000158380, {0xc000422010, 0x8, 0x8}, {0xc01ea80000, 0x2800000, 0x2800000}, {0xc044280000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc000351f70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0x0?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
panic: cipher.NewCBCEncrypter: IV length must equal block size

goroutine 65 [running]:
crypto/cipher.NewCBCEncrypter({0xbf2998, 0xc000698030}, {0xc0008fbed8, 0x8, 0x8})
	/usr/local/go/src/crypto/cipher/cbc.go:47 +0xcc
github.com/cyverse/go-irodsclient/irods/util.encryptAES256CBC({0xc0001fc620?, 0xc000363918?, 0xc00084a020?}, {0xc0008fbed8, 0x8, 0x8}, {0xc00d280000, 0x2800000, 0x2800000}, {0xc026280000, ...})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:85 +0xba
github.com/cyverse/go-irodsclient/irods/util.Encrypt({0xaf6247, 0xb}, {0xc0001fc620, 0x20, 0x20}, {0xc0008fbed8, 0x8, 0x8}, {0xc00d280000, 0x2800000, ...}, ...)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/util/encryption.go:19 +0x192
github.com/cyverse/go-irodsclient/irods/connection.(*IRODSResourceServerConnection).Encrypt(0xc000158480, {0xc0008fbed8, 0x8, 0x8}, {0xc00d280000, 0x2800000, 0x2800000}, {0xc026280000, 0x5000000, 0x5000000})
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/connection/resource_server_connection.go:437 +0x119
github.com/cyverse/go-irodsclient/irods/fs.uploadDataObjectChunkToResourceServer(0xc000312000?, 0xc000272480, 0xc000392190, {0xc00016eaa0, 0x43}, 0xc000363f70)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:425 +0x9ef
github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer.func1(0x0?)
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:684 +0x155
created by github.com/cyverse/go-irodsclient/irods/fs.UploadDataObjectToResourceServer
	/go/pkg/mod/github.com/cyverse/go-irodsclient@v0.14.4/irods/fs/data_object_resource_server.go:694 +0xd1f
[koehorst@int4 ~]$ 
```

any clue what goes wrong?

**Comment by iychoi** [comment]
Hi @jjkoehorst
It looks like the new put implementation with `redirect-to-resource` failed to encrypt/decrypt packets.

Can you answer these questions to track down the issue?
- Do you use SSL/PAM for auth?
- Does `sync` work with `--icat`? You can add `--icat` option to disable the `redirect-to-resource` feature.

The message says, the length of encryption initial vector (IV) is not matching to expected length. I wasn't able to test the new `redirect-to-resource` feature thoroughly. Maybe the feature is the evil.

**Comment by iychoi** [comment]
I was able to reproduce the issue. I'll try to fix it tomorrow!

**Comment by iychoi** [comment]
Fixed the issue at the recent release. Please check it out and reopen the issue if it still occurs.

https://github.com/cyverse/gocommands/releases/tag/v0.9.6
