### ISSUE TITLE
`signal SIGSEGV` error while putting in wrong path/inexistent directory

### ISSUE THREAD

**Issue by mstfdkmn** [cyverse/gocommands#59]
`gocmd ls` and `gocmd get` return correct/expected error but `gocmd put` command returns the error below:

```
root@cfd7c8faf640:/# gocmd get icts/home/u0137480/hello.txt
File or directory "/icts/home/u0137480/icts/home/u0137480/hello.txt" is not found!
root@cfd7c8faf640:/# gocmd ls icts/home/u0137480
File or directory "/icts/home/u0137480/icts/home/u0137480" is not found!
root@cfd7c8faf640:/# gocmd put test.txt icts/home/u0137480
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9bebda]

goroutine 1 [running]:
github.com/cyverse/gocommands/cmd/subcmd.(*PutCommand).requireEncryption(0xc000204680, {0xc0003b19e0, 0x26}, 0x13?, {0x0, 0x0})
        /github/workspace/cmd/subcmd/put.go:291 +0xfa
github.com/cyverse/gocommands/cmd/subcmd.(*PutCommand).putOne(0xc000204680, {0x7fff829d5650, 0x8}, {0x7fff829d5659, 0x12})
        /github/workspace/cmd/subcmd/put.go:343 +0x331
github.com/cyverse/gocommands/cmd/subcmd.(*PutCommand).Process(0xc000204680)
        /github/workspace/cmd/subcmd/put.go:215 +0xcf6
github.com/cyverse/gocommands/cmd/subcmd.processPutCommand(0xff6360?, {0xc0002004c0?, 0x2?, 0x2?})
        /github/workspace/cmd/subcmd/put.go:62 +0x3a
github.com/spf13/cobra.(*Command).execute(0xff6360, {0xc000200480, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xff8160)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.Execute(...)
        /github/workspace/cmd/gocmd.go:32
main.main()
        /github/workspace/cmd/gocmd.go:107 +0x372

```

**Comment by iychoi** [comment]
Can you quick check your gocmd version using `gocmd -v`? I guess you are running an old version of gocmd. I am not able to reproduce the issue with the latest version.

**Comment by mstfdkmn** [comment]
```
root@a09b9e6aba0e:/# gocmd -v
{
  "clientVersion": "v0.9.14",
  "gitCommit": "d08d8c439de7bd00a2d56747eda3361e9810019e",
  "buildDate": "2024-09-04T20:23:21Z",
  "goVersion": "go1.18.6",
  "compiler": "gc",
  "platform": "linux/amd64"
}

```

**Comment by mstfdkmn** [comment]
After I run the "upgrade" command, seem it is working as expected. Thanks.

root@a09b9e6aba0e:/# gocmd upgrade
root@a09b9e6aba0e:/# gocmd -v
{
  "clientVersion": "v0.10.3",
  "gitCommit": "ca15fe168e86390877b99e7dec1d977a6a7ed5ae",
  "buildDate": "2024-09-27T23:51:08Z",
  "goVersion": "go1.18.6",
  "compiler": "gc",
  "platform": "linux/amd64"
}
root@a09b9e6aba0e:/# gocmd put test.txt icts/home/u0137480
iRODS Error (code: '-814000', message: "CAT_UNKNOWN_COLLECTION")
 
```

**Comment by iychoi** [comment]
Thanks for checking!

**Comment by iychoi** [comment]
The iRODS Error `CAT_UNKNOWN_COLLECTION` will be translated as `file not found error` in gocommands correctly at commit 474c7dd058ae163cf3e38cba2f565f4173dc7035.
