### ISSUE TITLE
Possible Gocommands v0.10.5 issue with 32-bit Windows

### ISSUE THREAD

**Issue by jnimoth** [cyverse/gocommands#60]
Hi Illyoung,
we have a machine that transfers data to our iRODS system using gocommands. The system is a 32-bit Windows installation and it was working before our upgrade to 4.3.2.
They now upgraded via `gocmd upgrade` today to get the new version that runs with 4.3.2 (platform: windows/386).

After that, everything seemed to work fine at first (`gocmd ls` and similar worked for example), but there was an issue when trying to upload data.

Here the error message:

```
PS C:\> .\rdms\gocmd.exe --config C:\rdms\gocmd_creds.yaml put -k --diff --debug C:\frames\2024\ /rug/home/user@rug.n
l/
time="2024-11-27 15:18:42.252" level=debug msg="use sessionID - 2548" function=ProcessCommonFlags package=flag
time="2024-11-27 15:18:42.285" level=debug msg="reading icommands configuration file \"C:\\\\rdms\\\\gocmd_creds.yaml\""
 function=Load package=icommands struct=ICommandsEnvironmentManager
time="2024-11-27 15:18:42.288" level=debug msg="Connecting to store.data.rug.nl:1247" function=connectTCP package=connec
tion struct=IRODSConnection
time="2024-11-27 15:18:42.294" level=debug msg="Start up an iRODS connection" function=startup package=connection struct
=IRODSConnection
time="2024-11-27 15:18:42.580" level=debug msg="Start up CS Negotiation" function=startup package=connection struct=IROD
SConnection
time="2024-11-27 15:18:42.580" level=debug msg="Client policy \"CS_NEG_REQUIRE\", server policy \"CS_NEG_DONT_CARE\"" fu
nction=startup package=connection struct=IRODSConnection
time="2024-11-27 15:18:42.580" level=debug msg="Start up SSL" function=sslStartup package=connection struct=IRODSConnect
ion
time="2024-11-27 15:18:42.647" level=debug msg="Logging in using pam authentication method" function=loginPAMWithPasswor
d package=connection struct=IRODSConnection
time="2024-11-27 15:18:42.647" level=debug msg="use auth plugin api: scheme \"pam\"" function=loginPAMWithPassword packa
ge=connection struct=IRODSConnection
time="2024-11-27 15:18:43.493" level=debug msg="Connecting to store.data.rug.nl:1247" function=connectTCP package=connec
tion struct=IRODSConnection
time="2024-11-27 15:18:43.493" level=debug msg="Start up an iRODS connection" function=startup package=connection struct
=IRODSConnection
time="2024-11-27 15:18:43.759" level=debug msg="Start up CS Negotiation" function=startup package=connection struct=IROD
SConnection
time="2024-11-27 15:18:43.759" level=debug msg="Client policy \"CS_NEG_REQUIRE\", server policy \"CS_NEG_DONT_CARE\"" fu
nction=startup package=connection struct=IRODSConnection
time="2024-11-27 15:18:43.775" level=debug msg="Start up SSL" function=sslStartup package=connection struct=IRODSConnect
ion
time="2024-11-27 15:18:43.808" level=debug msg="Logging in using pam authentication method" function=loginPAMWithToken p
ackage=connection struct=IRODSConnection
time="2024-11-27 15:18:43.918" level=debug msg="start job run thread" function=Start package=commons struct=ParallelJobM
anager
time="2024-11-27 15:18:43.918" level=debug msg="Reuse an idle connection" function=Get package=session struct=Connection
Pool
time="2024-11-27 15:18:43.934" level=debug msg="failed to commit transaction" error=SYS_NO_API_PRIV function=endTransact
ion package=session struct=IRODSSession
time="2024-11-27 15:18:43.934" level=debug msg="Returning a connection" function=Return package=session struct=Connectio
nPool
time="2024-11-27 15:18:43.934" level=debug msg="Reuse an idle connection" function=Get package=session struct=Connection
Pool
time="2024-11-27 15:18:43.954" level=debug msg="Returning a connection" function=Return package=session struct=Connectio
nPool
time="2024-11-27 15:18:43.954" level=debug msg="Reuse an idle connection" function=Get package=session struct=Connection
Pool
time="2024-11-27 15:18:43.970" level=debug msg="Returning a connection" function=Return package=session struct=Connectio
nPool
time="2024-11-27 15:18:43.970" level=debug msg="Reuse an idle connection" function=Get package=session struct=Connection
Pool
time="2024-11-27 15:18:43.989" level=debug msg="Returning a connection" function=Return package=session struct=Connectio
nPool
time="2024-11-27 15:18:43.989" level=debug msg="Reuse an idle connection" function=Get package=session struct=Connection
Pool
time="2024-11-27 15:18:44.005" level=debug msg="Returning a connection" function=Return package=session struct=Connectio
nPool
time="2024-11-27 15:18:44.005" level=debug msg="# threads : 1, max 5" function=Start package=commons struct=ParallelJobM
anager
time="2024-11-27 15:18:44.005" level=debug msg="Disconnecting the connection" function=Disconnect package=connection str
uct=IRODSConnection
time="2024-11-27 15:18:44.005" level=debug msg="Run job 0, \"C:\\\\frames\\\\2024\\\\AgBh_104cm_vac_20mA_0_001.gfrm\"" f
unction=Start package=commons struct=ParallelJobManager
time="2024-11-27 15:18:44.005" level=debug msg="uploading a file \"C:\\\\frames\\\\2024\\\\AgBh_104cm_vac_20mA_0_001.gfr
m\" to \"/rug/home/user@rug.nl/2024/AgBh_104cm_vac_20mA_0_001.gfrm\"" function=schedulePut package=subcmd struct=PutC
ommand
time="2024-11-27 15:18:44.022" level=debug msg="Connecting to store.data.rug.nl:1247" function=connectTCP package=connec
tion struct=IRODSConnection
time="2024-11-27 15:18:44.027" level=debug msg="Start up an iRODS connection" function=startup package=connection struct
=IRODSConnection
panic: unaligned 64-bit atomic operation

goroutine 1 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x12dc81e4, 0x1)
        /usr/local/go/src/runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/cyverse/gocommands/commons.(*ParallelJobManager).Schedule(0x12dc8180, {0x12e962a0, 0x2d}, 0x12e87000, 0x1, {0
xb4871c, {0x0, 0x0}, 0x0})
        /github/workspace/commons/parallel.go:133 +0x1a7
github.com/cyverse/gocommands/cmd/subcmd.(*PutCommand).schedulePut(0x12d98c40, {0xc03fa4, 0x12ea8a20}, {0x12e962a0, 0x2d
}, {0x0, 0x0}, {0x12e949c0, 0x3c}, 0x0, ...)
        /github/workspace/cmd/subcmd/put.go:434 +0x389
github.com/cyverse/gocommands/cmd/subcmd.(*PutCommand).putFile(0x12d98c40, {0xc03fa4, 0x12ea8a20}, {0x12e962a0, 0x2d}, {
0x0, 0x0}, {0x12e949c0, 0x3c}, 0x0, ...)
        /github/workspace/cmd/subcmd/put.go:458 +0x12a3
github.com/cyverse/gocommands/cmd/subcmd.(*PutCommand).putDir(0x12d98c40, {0xc03fa4, 0x12dceae0}, {0x12dc2ed0, 0xe}, {0x
12e98180, 0x1d}, 0x0, {0x0, 0x0})
        /github/workspace/cmd/subcmd/put.go:739 +0xf24
github.com/cyverse/gocommands/cmd/subcmd.(*PutCommand).putOne(0x12d98c40, {0x12c10120, 0xf}, {0x12c162a0, 0x19})
        /github/workspace/cmd/subcmd/put.go:328 +0x31a
github.com/cyverse/gocommands/cmd/subcmd.(*PutCommand).Process(0x12d98c40)
        /github/workspace/cmd/subcmd/put.go:204 +0x904
github.com/cyverse/gocommands/cmd/subcmd.processPutCommand(0xfc07e0, {0x12d89c80, 0x2, 0x7})
        /github/workspace/cmd/subcmd/put.go:62 +0x61
github.com/spf13/cobra.(*Command).execute(0xfc07e0, {0x12d89c40, 0x7, 0x8})
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x686
github.com/spf13/cobra.(*Command).ExecuteC(0xfc1860)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x403
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.Execute(...)
        /github/workspace/cmd/gocmd.go:32
main.main()
        /github/workspace/cmd/gocmd.go:107 +0x3a6

```

**Comment by iychoi** [comment]
Hi,

Would you try the new release? It was 64bit alignment issue only occurs on 32bit machine. I wasn't able to test it as I don't have 32bit system. Let me know how it goes.

https://github.com/cyverse/gocommands/releases/tag/v0.10.6

**Comment by jnimoth** [comment]
Thanks.
Next week I can again try on a 32bit system

**Comment by iychoi** [comment]
Great! Thank you for update.
